import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import QueryProvider from "./queryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Woov Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className=" bg-[#131313] flex h-screen  ">
            <div className="h-screen  z-20 fixed flex items-center px-1">
              <Sidebar />
            </div>
            <div className=" scrollbar-hide w-full overflow-y-scroll sm:pl-[8vw]  md:pl-[7vw] px-[4vw] md:pr-[2.5vw]   ">
              <Navbar />
              <div className="content-area ">{children}</div>
            </div>
          </div>
        </body>
      </QueryProvider>
    </html>
  );
}
